@startuml
class ChangeSubMenuGUI {
    + buttonsList : List<Button>
    - changeSubmenuEventList : List<ChangeSubmenuEvent>
    + GetSubmenuEventsList() : List<ChangeSubmenuEvent>
    - OnEnable() : void
    - ResetButtons() : void
    - AssignNewButtonColor(button:Button, color:Color) : void
    + OnChangeSubmenuButtonEvent(button:Button, buttonType:MenuEventType, color:Color) : void
}
MonoBehaviour <|-- ChangeSubMenuGUI
@enduml
