@startuml
class CheckConnection {
    - display : TMP_Text
    + apiPetitions : ZabbixPetitions
    - Start() : void
    + Check() : IEnumerator
    - MakeLogInPetition() : IEnumerator
    - ManageErrorFromWebRequest(www:UnityWebRequest) : string
    + MakeWarningsPetition() : void
}
MonoBehaviour <|-- CheckConnection
@enduml
