@startuml
!include .\\ChangeSubMenuGUI.puml
!include .\\CheckConnection.puml
!include .\\Inicio.puml
!include .\\ListOfComponentsGUI.puml
!include .\\MenuEvents.puml
!include .\\MenuEventType.puml
!include .\\RotateObjectWithSlider.puml
!include .\\SelectRackController.puml
!include .\\ServerAnim.puml
!include .\\TesterScript.puml
!include .\\Architecture\ArchitectureGeneralManager.puml
!include .\\Architecture\ArchitectureObjectsManager.puml
!include .\\Architecture\ArchitectureXmlManager1.puml
!include .\\GameObjectScripts\ControllersList.puml
!include .\\GameObjectScripts\ElementController.puml
!include .\\GameObjectScripts\IndicatorController.puml
!include .\\GameObjectScripts\IndicatorPanelController.puml
!include .\\GameObjectScripts\IndicatorPanelManager.puml
!include .\\GameObjectScripts\MoveSlotAnimation.puml
!include .\\GameObjectScripts\ScriptPanelInfo.puml
!include .\\GameObjectScripts\VirtualButtonBehaviour.puml
!include .\\GameObjectScripts\WarningController.puml
!include .\\SceneManagers\ErrorManager.puml
!include .\\SceneManagers\ErrorManagerGUI.puml
!include .\\SceneManagers\ExitMenuController.puml
!include .\\SceneManagers\LogInUIElementsController.puml
!include .\\Scriptable\SubMenuButton.puml
!include .\\UI\SubMenuButtonFunctionality.puml
!include .\\UI\SubMenuLayoutFunctionality.puml
!include .\\VMDC_Scripts\DTOs.puml
!include .\\VMDC_Scripts\ExtraClassesAndMethods_Zabbity.puml
!include .\\VMDC_Scripts\ResponseAPIClasses.puml
!include .\\VMDC_Scripts\SlotDataAndControl.puml
!include .\\VMDC_Scripts\SlotDataFromAPI_Manager.puml
!include .\\VMDC_Scripts\SlotRackInteraction.puml
!include .\\VMDC_Scripts\StaticDataHolder.puml
!include .\\VMDC_Scripts\VMDC_AuxiliarConfiguration.puml
!include .\\VMDC_Scripts\VMDC_Constants.puml
!include .\\VMDC_Scripts\ZabbixPetitions.puml
@enduml
