@startuml
class Inicio {
    + selectRack : GameObject
    + guiSlot : GameObject
    + guiSlotServerTest : GameObject
    + rotationGui : float = 290
    + callForArchitecture : bool = true
    + callForZabbixData : bool = true
    + slotDFAM : SlotDataFromAPI_Manager
    + architectureGeneralManager : ArchitectureGeneralManager
    - Start() : void
    - UpdateDataCoroutine() : IEnumerator
}
MonoBehaviour <|-- Inicio
@enduml
