@startuml
class SelectRackController {
    - gameObjectWithRenderer : GameObject
    - originalMat : Material
    - original : bool = true
    - Start() : void
    + ChangeColor(newMat:Material) : void
}
MonoBehaviour <|-- SelectRackController
@enduml
