@startuml
class ServerAnim {
    + animator : Animator
    - serverIsOpen : bool = false
    + slotName : string
    + gui : GameObject
    - boxCollider : BoxCollider
    - OnEnable() : void
    - Start() : void
    + OpenServerAnim() : void
    - AsignSlotNameToGUI() : void
}
MonoBehaviour <|-- ServerAnim
@enduml
