@startuml
class TesterScript {
    + ShowLog(log:string) : void
    + ActivateItem(gameObject:GameObject) : void
    + ChangeColor(newColor:string, gameObject:GameObject) : void
}
MonoBehaviour <|-- TesterScript
@enduml
