@startuml
class IndicatorPanelController {
    - indicatorPanelManager : IndicatorPanelManager
    - normalPanelData : PanelSemaforoData
    - vmPanelData : PanelSemaforoData
    - normalSemaforos : List<GameObject>
    - vmSemaforos : List<GameObject>
    - usingVmSemaforos : bool = false
    + panelSemaforo : GameObject
    + panelInicial : GameObject
    + errorPanel : GameObject
    + listaElementos : GameObject
    - scriptPanel : ScriptPanelInfo
    - errorText : Text
    - originalErrorText : string
    - initialized : bool = false
    - OnEnable() : void
    - Inicialize() : void
    + RestoreErrorText() : void
    + SetErrorText(error:string) : void
    + GetScriptPanelInfo() : ScriptPanelInfo
    + StartPanelAndSaveApiSchema(type:string) : DataApiSchema
    - ApplyPanelSettings(panelData:PanelSemaforoData) : void
    - InstanceSemaforosPanel(listSemaforos:List<SemaforoData>, isVM:bool) : void
    - ApplyColor(image:Image, newColor:string) : void
    + UpdateDataButtons() : IEnumerator
    - ScriptList(gameObjectList:List<GameObject>) : List<IndicatorController>
    + IsVmCanvas(vmMode:bool) : void
    + ManageErrorPanel() : void
    + ButtonWithIDHasBeenPressed(buttonID:int) : bool
    + HideInfo() : void
}
MonoBehaviour <|-- IndicatorPanelController
@enduml
