@startuml
class IndicatorPanelManager {
    - panelInterfaceList : List<PanelSemaforoData>
    - panelSemaforoList : List<SemaforoData>
    - listKeyModel : List<KeyModel>
    - OnEnable() : void
    - SetSemaforoDataToInterface() : void
    - GetKeyModelFromKeyID(keyID:string) : KeyModel
    + GetPanelData(type:string) : PanelSemaforoData
    + UpdateKeyValueModels() : void
}
MonoBehaviour <|-- IndicatorPanelManager
@enduml
