@startuml
class MoveSlotAnimation {
    - auxCanvas : GameObject
    - mainCanvasPanel : GameObject
    - startPos : Vector3
    - Start() : void
    + SetCanvasAnimation(mainPanel:GameObject, canvas:GameObject) : void
    + DoAnimation(isClosed:bool) : void
    + OpenAnimation() : void
    + CloseAnimation() : void
    + ActivatePanel() : void
    + DeactivatePanel() : void
    - MoveToSpot(Gotoposition:Vector3) : IEnumerator
}
MonoBehaviour <|-- MoveSlotAnimation
@enduml
