@startuml
class LogInUIElementsController {
    + serverIpText : Text
    + buttonLogIn : Button
    + loadingCircle : GameObject
    + username : InputField
    + password : InputField
    + errorText : Text
    - isLoading : bool
    - Start() : void
    - Update() : void
    + UpdateServerIPText() : void
    + StartLogIn() : void
    + EndLogIn() : void
    - CheckInputFields() : void
    - ManageAllInputs(active:bool) : void
    + DeactivateInitialButtons() : void
    + ActivateInitialButtons() : void
    + RefreshErrorText() : void
}
MonoBehaviour <|-- LogInUIElementsController
@enduml
