@startuml
class SubMenuButtonFunctionality {
    - buttonType : MenuEventType
    - newButtonColor : Color
    + isDefaultMode : bool
    - Start() : void
    - FixedUpdate() : void
    + SendOnClickEvent() : void
    + onChangeSubmenuButtonEvent : ChangeSubmenuButtonEvent
    + onChangeSubmenuEvent : ChangeSubmenuEvent
}
MonoBehaviour <|-- SubMenuButtonFunctionality
@enduml
