@startuml
class WarningData {
    + priority : int <<get>> <<set>>
    + lastEvent : WarningEvent <<get>> <<set>>
}
class WarningEvent {
    + name : string <<get>> <<set>>
    + severity : string <<get>> <<set>>
}
class ResponseIdHosts {
    + jsonrpc : string = "2.0"
    + result : List<IdHostsData> <<get>> <<set>>
    + id : int <<get>> <<set>>
}
class IdHostsData {
    + hostid : string <<get>> <<set>>
    + name : string <<get>> <<set>>
    + host : string <<get>> <<set>>
    + description : string <<get>> <<set>>
    + interfaces : List<IdHostInterface> <<get>> <<set>>
}
class IdHostInterface {
    + interfaceid : string <<get>> <<set>>
    + ip : string <<get>> <<set>>
}
class ResponseHostGroup {
    + jsonrpc : string = "2.0"
    + result : List<HostGroupsData> <<get>> <<set>>
    + id : int <<get>> <<set>>
}
class HostGroupsData {
    + groupid : string <<get>> <<set>>
    + name : string <<get>> <<set>>
}
class Request {
    + jsonrpc : string = "2.0"
    + method : string <<get>> <<set>>
    + @params : Dictionary<string, System.Object> <<get>> <<set>>
    + id : int <<get>> <<set>>
    + auth : string <<get>> <<set>>
    + Request(method:string, @params:Dictionary<string, System.Object>, id:int, auth:string)
    + addParam(key:string, value:string) : void
}
class Response {
    + jsonrpc : string = "2.0"
    + result : List<System.Object> <<get>> <<set>>
    + id : int <<get>> <<set>>
    + Response(result:List<System.Object>, id:int)
    + addResult(result:List<System.Object>) : void
}
class ResponseLoggin {
    + jsonrpc : string = "2.0"
    + result : string <<get>> <<set>>
    + id : int <<get>> <<set>>
}
class ResponseItems {
    + jsonrpc : string = "2.0"
    + result : List<ResponseItem> <<get>> <<set>>
    + id : int <<get>> <<set>>
}
class ResponseItem {
    + description : string <<get>> <<set>>
    + key_ : string <<get>> <<set>>
    + name : string <<get>> <<set>>
    + lastvalue : string <<get>> <<set>>
}
@enduml
