@startuml
class SlotDataAndControl {
    + hostID : string
    + ip : string
    + slotNum : int
    + slotName : string
    + type : string
    + hostname : string
    + host : string
    + descriptionHost : string
    + dataApiSchema : DataApiSchema
    + dataApiContainer : DataApiContainer
    + hostGroupID : string
    + virtualMachinesList : List<VMData>
    + checkSlotDemoMode : bool = false
    + slotIsDeactivated : bool = false
    + isRefreshing : bool = true
    + refreshTime : float
}
MonoBehaviour <|-- SlotDataAndControl
@enduml
