@startuml
class ZabbixConfigInfo {
    + ZabbixConfigInfo(ip:string, urlAPI:string, urlFiles:string)
    + ipServer : string
    + urlZabbixAPI : string
    + urlConfigurationFiles : string
}
class ZabbixConfigFile <<static>> {
    + {static} setConfig() : bool
    - {static} SetValues(ipServer:string, urlZabbixAPI:string, urlConfigurationFiles:string) : void
    - {static} CheckIfFileExistsAndCreateIfNot() : bool
    + {static} SaveAndWriteNewConfiguration(ipServer:string, urlZabbixAPI:string, urlConfigurationFiles:string) : bool
    - {static} ReadFile(file:string) : string
    + {static} SetConfigFileToDefault() : void
    - {static} WriteVMDCConfigToFile(path:string) : bool
    + {static} SetDefaultConfigFromDefaultFile() : void
    - {static} SetDefaultValues(ipServer:string, urlZabbixAPI:string, urlConfigurationFiles:string) : void
}
class ZabbixConfig <<static>> {
    + {static} authKey : string <<get>> <<set>>
    + {static} ipServer : string <<get>> <<set>>
    + {static} urlZabbixAPI : string <<get>> <<set>>
    + {static} urlConfigurationFiles : string <<get>> <<set>>
}
class ZabbixConfigDefault <<static>> {
    + {static} ipServer : string <<get>> <<set>>
    + {static} urlZabbixAPI : string <<get>> <<set>>
    + {static} urlConfigurationFiles : string <<get>> <<set>>
}
@enduml
