@startuml
class VMDCPaths <<static>> {
    + {static} extraFilesDirName : string = "ConfigurationFiles"
    + {static} extraFilesDirPath : string
    + {static} logFilePath : string
    + {static} architectureName : string = "Architecture_SalaCPD.xml"
    + {static} architecturePath : string
    + {static} modelsRackName : string = "RackDataModels.xml"
    + {static} modelsRackPath : string
    + {static} configFilePath : string
    + {static} defaultConfigFilePath : string
    + {static} racksModelsPath : string = "RacksModels/"
    + {static} slotsModelsPath : string = "SlotModels/"
    + {static} othersModelsPath : string = "OthersModels/"
    + {static} slotsSpritesPath : string = "SlotSprites/"
    + {static} KeyValueModelsName : string = "KeyValueModels.xml"
    + {static} KeyValueModelsPath : string
    + {static} panelSemaforoModelsName : string = "PanelSemaforoModels.xml"
    + {static} panelSemaforoModelsPath : string
    + {static} interfacesSemaforoModelsName : string = "InterfacesSemaforoModels.xml"
    + {static} interfacesSemaforoModelsPath : string
    + {static} semaforoPrefabPath : string = "OthersModels/semaforoModel"
}
class VMDCErrorCodes <<static>> {
    + <<const>> NON_RESPONSE_API_ERROR : string = "<color=red>ERROR</color>: No response from API Zabbix"
}
class VMDCTags <<static>> {
    + <<const>> VIRTUAL_MACHINE_TAG : string = "virtualMachine"
}
@enduml
