@startuml
class ArchitectureGeneralManager {
    - objectsManager : ArchitectureObjectsManager
    - xmlManager : ArchitectureXmlManager
    - architectureRawData : ArchitectureRawData
    - loginController : LogInUIElementsController
    + Initialize() : bool
    + LoadArchitectureData() : void
    + GetArchitectureRawData() : ArchitectureRawData
    + SetObjectsFromData() : void
}
MonoBehaviour <|-- ArchitectureGeneralManager
@enduml
