@startuml
class SlotRackInteraction {
    - slotDaC : SlotDataAndControl
    - slotDFAM : SlotDataFromAPI_Manager
    - originalHostID : string
    - originalHostname : string
    - originalDataApiSchema : DataApiSchema
    - vmDataApiSchema : DataApiSchema
    + slotHoverInfo : GameObject
    + slotInfo : Text
    + warningController : WarningController
    + titleHeader : Text
    - slotAnimation : MoveSlotAnimation
    - slotIsClosed : bool = true
    - newdata : bool = true
    + mainCanvasPanel : GameObject
    + loadingIcon : GameObject
    + auxCanvas : GameObject
    - dataButtons : Component[]
    + slotHalo : Behaviour
    + indicatorPanelController : IndicatorPanelController
    - vmUpdated : bool = false
    - vmNotInitialized : bool = false
    - doneWithUpdating : bool = false
    - Start() : void
    - StartSlot() : IEnumerator
    - OnMouseDown() : void
    - WaitAnimationUntilUpdateIsDone() : IEnumerator
    - Initialize(type:string) : void
    - OnMouseEnter() : void
    - OnMouseExit() : void
    + UpdateAllData() : void
    + UpdateMainData() : void
    + UpdateWarnings() : void
    + UpdateDataCoroutine() : IEnumerator
    + UpdateWarningsCoroutine() : IEnumerator
    + UpdateVMsCoroutine() : IEnumerator
    - GetVMKey() : string
    + EnterVM(hostid:string, vmHostname:string) : void
    + GetPanelCanvas() : GameObject
    - DeactivateSlotGraphics() : void
}
MonoBehaviour <|-- SlotRackInteraction
@enduml
